//
// Created by khuang on 6/25/18.
//

#ifndef MT_OBJSLAM_OBJSCENERECONSTRUCTIONENGINE_CPU_H
#define MT_OBJSLAM_OBJSCENERECONSTRUCTIONENGINE_CPU_H

class ObjSceneReconstructionEngine_CPU {

};

#endif //MT_OBJSLAM_OBJSCENERECONSTRUCTIONENGINE_CPU_H
